# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)




adventure = Category.create!(name: "Adventure")
family = Category.create!(name: "Family")
foodie = Category.create!(name: "Foodie")
artistic  = Category.create!(name: "Artistic")
adult = Category.create!(name: "Adult")


#bkb = Location.create!(name: 'Butcher Knife Brewery', address: '2875 Elk River Road, Steamboat Springs, CO 80487')
#spb = Location.create!(name: 'Storm Peak Brewery', address: '1885 Elk River Plaza, Steamboat Springs, CO 80487')
#mtb = Location.create!(name: 'Smell That Bread Bakery', address: '135 11th St, Steamboat Springs, CO 80487')
#pw = Location.create!(name: 'Potters Wheel Studio', address: '1280 13th St k, Steamboat Springs, CO 80487')
#ohanas = Location.create!(name: 'Ohanas Factory', address: '700 Yampa St a105, Steamboat Springs, CO 80487')
#wwb = Location.create!(name: 'Wild West Baloons HQ', address: '953 Dougherty Rd, Steamboat Springs, CO 80487')
#gondola = Location.create!(name: 'Steamboat Gondola', address: '2305 Mt Werner Cir #1, Steamboat Springs, CO 80487')


mk = Location.create!(name: 'Moose Knuckles', instruction: "10th Street South",  address: '1009 Lincoln Ave, Steamboat Springs, CO 80487')
Location.create!(name: 'Yampa Valley Medical Center', instruction: "Main Entrance",  address: '1024 Central Park Dr, Steamboat Springs, CO 80487')
Location.create!(name: 'Yampa Valley Medical Center ER', instruction: "ER Entrance",  address: '1024 Central Park Dr, Steamboat Springs, CO 80487')
Location.create!(name: 'Boomerangs', instruction: "10th Street South Shuttle Sign",  address: '1025 Lincoln Ave, Steamboat Springs, CO 80487 ')
Location.create!(name: 'Steamboat Meat & Seafood Company', instruction: "Front Entrance",  address: '1030 Yampa St, Steamboat Springs, CO 80488')
Location.create!(name: 'Steamboat Pilates Yoga & Fitness Studio', instruction: " Front of building-street side",  address: '1104 Lincoln Ave, Steamboat Springs, CO 80487')
Location.create!(name: "Dude and Dans Bar & Grill", instruction: "11th & Lincoln-shuttle stop sign",  address: '1106 Lincoln Ave, Steamboat Springs, CO 80487')
Location.create!(name: 'Yama Kawa', instruction: "Front Of Restaurant",  address: '1110 Yampa St, Steamboat Springs, CO 80487')
Location.create!(name: 'Double Z Bar & Bar-BQ ', instruction: "front of restaurant",  address: '1124 Yampa St, Steamboat Springs, CO 80487')
Location.create!(name: 'McDonalds', instruction: "Front of restaurant",  address: '1150 S Lincoln Ave, Steamboat Springs, CO 80477')
Location.create!(name: 'Azteca Taqueria', instruction: "9th st North Shuttle sign",  address: '116 9th St, Steamboat Springs, CO 80487')
Location.create!(name: 'Brick', instruction: "Front Entrance",  address: '1195 Bangtail Way, Steamboat Springs, CO 80487')
Location.create!(name: 'Steamboat Touring Center', instruction: "Front Entrance",  address: '1230 Steamboat Blvd, Steamboat Springs, CO 80487')
Location.create!(name: 'Creekside Café', instruction: "front of restaurant",  address: '131 11th St, Steamboat Springs, CO 80487')
Location.create!(name: 'Smell That Bread', instruction: "Front of store",  address: '135 11th St, Steamboat Springs, CO 80487')
Location.create!(name: 'Old Town Hot Springs', instruction: "Front of building",  address: '136 S Lincoln Ave, Steamboat Springs, CO 80487')
Location.create!(name: 'Walgreens', instruction: "Front of store",  address: '1440 Pine Grove Rd, Steamboat Springs, CO 80487')
Location.create!(name: 'Ski Haus Liquors/Conoco', instruction: "Parking Lot",  address: '1450 S Lincoln Ave, Steamboat Springs, CO 80487')
Location.create!(name: 'Ski Haus', instruction: "Front of store ",  address: '1457 Pine Grove Rd, Steamboat Springs, CO 80487')
Location.create!(name: 'Ore House', instruction: "Front of restaurant",  address: '1465 Pine Grove Rd, Steamboat Springs, CO 80487')
Location.create!(name: 'Steamboat Medical', instruction: "Front of Building (Ore House side)",  address: '1475 Pine Grove Rd #102, Steamboat Springs, CO 80487')
Location.create!(name: 'Soda Creek Pizza', instruction: "Front Entrance",  address: '1585 Mid Valley Dr, Steamboat Springs, CO 80487')
Location.create!(name: 'Townies', instruction: "Front of building",  address: '1744 Lincoln Ave Suite 4, Steamboat Springs, CO 80477')
Location.create!(name: 'Qdoba', instruction: "front of restaurant",  address: '1755 Central Park Dr Suite 116, Steamboat Springs, CO 80488')
annies = Location.create!(name: 'Annies', instruction: "Front of store",  address: '1755 Central Park Dr, Steamboat Springs, CO 80487')
Location.create!(name: 'La Fiesta Grill & Cantina', instruction: "front of restaurant",  address: '1755 Central Park Dr, Steamboat Springs, CO 80487')
Location.create!(name: 'The Golden Leaf', instruction: "front of building",  address: '1755 Lincoln Ave, Steamboat Springs, CO 80487')
Location.create!(name: "Trappuers Crossing", instruction: "Front office",  address: '1795 Medicine Springs Dr, Steamboat Springs, CO 80487')
Location.create!(name: 'Wal Mart', instruction: "Front of store under Pharmacy Sign",  address: '1805 Central Park Dr, Steamboat Springs, CO 80487')
Location.create!(name: 'Exclusive Nails in Central Park', instruction: "Front of City Market (yellow pillars)",  address: '1815 Central Park Dr # 107, Steamboat Springs, CO 80487')
Location.create!(name: 'City Market', instruction: "Front of store (yellow pillars)",  address: '1825 Central Park Dr, Steamboat Springs, CO 80477')
Location.create!(name: 'Central park liquor  ', instruction: "Front of City Market (yellow pillars)",  address: '1825 Central Park Dr, Steamboat Springs, CO 80477')
Location.create!(name: 'Smoker Friendly ', instruction: "Front of City Market (yellow pillars) ",  address: '1825 Central Park Dr, Steamboat Springs, CO 80477')
Location.create!(name: 'Colorado Bagel Company   ', instruction: "Front of City Market (yellow pillars)",  address: '1825 Central Park Dr, Steamboat Springs, CO 80477')
Location.create!(name: 'Christy Sports Central Park', instruction: "Front of store",  address: '1835 Central Park Dr, Steamboat Springs, CO 80487')
Location.create!(name: 'Café Diva', instruction: "Front of restaurant street side",  address: '1855 Ski Time Square Dr, Steamboat Springs, CO 80487')
Location.create!(name: 'Terry sports', instruction: "next to Café Diva Street side shuttle pick up",  address: '1855 Ski Time Square Dr, Steamboat Springs, CO 80487')
Location.create!(name: 'Slopeside  ', instruction: "next to Café Diva Street side shuttle pick up",  address: '1855 Ski Time Square Dr, Steamboat Springs, CO 80487')
Location.create!(name: 'Los Locos ', instruction: "next to Café Diva Street side shuttle pick up",  address: '1855 Ski Time Square Dr, Steamboat Springs, CO 80487')
Location.create!(name: 'Torian Plum', instruction: "next to Café Diva Street side shuttle pick up",  address: '1855 Ski Time Square Dr, Steamboat Springs, CO 80487')
Location.create!(name: 'Silver Lining  ', instruction: "next to Café Diva Street side shuttle pick up",  address: '1855 Ski Time Square Dr, Steamboat Springs, CO 80487')
Location.create!(name: 'Paramount ', instruction: "next to Café Diva Street side shuttle pick up",  address: '1855 Ski Time Square Dr, Steamboat Springs, CO 80487')
Location.create!(name: 'Anytime Fitness', instruction: "Front of building",  address: '1875 Central Park Dr, Steamboat Springs, CO 80477')
Location.create!(name: 'Creekside Teaze', instruction: "front of store",  address: '1875 Ski Time Square Dr, Steamboat Springs, CO 80487')
Location.create!(name: 'Storm Peak ', instruction: "front of restaurant",  address: '1885 Elk River Plaza, Steamboat Springs, CO 80487')
Location.create!(name: 'Moes', instruction: "front of restaurant ",  address: '1898 Kamar Plaza, Steamboat Springs, CO 80487')
Location.create!(name: 'Post Office', instruction: "front of building",  address: '200 Lincoln Ave, Steamboat Springs, CO 80487')
Location.create!(name: 'Kutuk', instruction: "Bottom of the stairs (RLC Shuttle Stop sign)",  address: '2000 ski time square drive, Steamboat Springs, CO 80487')
Location.create!(name: 'Rabbit Ears Motel', instruction: "front office ",  address: '201 Lincoln Ave, Steamboat Springs, CO 80487')
Location.create!(name: "Timber Run", instruction: "front office",  address: "2015 Walton Creek Rd, Steamboat Springs, CO 80487")
Location.create!(name: "T-Bar", instruction: "front of restaurant",  address: "2045 Ski Time Square Dr, Steamboat Springs, CO 80487")
Location.create!(name: "Cloverdale", instruction: "front of restaurant",  address: "207 9th St, Steamboat Springs, CO 80487")
Location.create!(name: "Snow Bowl", instruction: "front entrance",  address: "2090 Snow Bowl Plaza, Steamboat Springs, CO 80487")
Location.create!(name: "Big House Burgers", instruction: "front of restaurant",  address: "2093 Curve Plaza # 101, Steamboat Springs, CO 80487")
Location.create!(name: "Ace Hardware", instruction: "front of store",  address: "2155 Curve Plaza, Steamboat Springs, CO 80487")
Location.create!(name: "Three Peaks Grill", instruction: "front of restaurant",  address: "2165 Pine Grove Rd, Steamboat Springs, CO 80487")
Location.create!(name: "Sheraton", instruction: "Front Lobby",  address: "2200 Village Inn Ct, Steamboat Springs, CO 80487")
Location.create!(name: "Rocky Mountain Day Spa", instruction: "Front of Sheraton",  address: "2200 Village Inn Ct, Steamboat Springs, CO 80487")
Location.create!(name: "Antlers", instruction: "Front of building street side",  address: "2215 Storm Meadows Dr, Steamboat Springs, CO 80487")
Location.create!(name: "Starbucks (hwy 40)", instruction: "Front of restaurant",  address: "225 Anglers Dr, Steamboat Springs, CO 80487")
Location.create!(name: "One Steamboat Place", instruction: "front of building",  address: "2250 Apres Ski Way, Steamboat Springs, CO 80487")
Location.create!(name: "Gondola Transit Center", instruction: "lanes 2,3", address: "2291 Mt Werner Cir, Steamboat Springs, CO 80487")
Location.create!(name: "Christy Sports", instruction: "Gondola Square Gondola Transit Center", address: "2291 Mt Werner Cir, Steamboat Springs, CO 80487")
Location.create!(name: "Truffle Pig", instruction: "Gondola Transit Center", address: "2291 Mt Werner Cir, Steamboat Springs, CO 80487")
Location.create!(name: "Gondola Pub and Grill", instruction: "Gondola Transit Center", address: "2291 Mt Werner Cir, Steamboat Springs, CO 80487")
Location.create!(name: "Bear River Bar and Grill", instruction: "Gondola Transit Center", address: "2291 Mt Werner Cir, Steamboat Springs, CO 80487")
Location.create!(name: "Upper Knoll Lot", instruction: "Gondola Transit Center", address: "2291 Mt Werner Cir, Steamboat Springs, CO 80487")
Location.create!(name: "Music Festival Tent", instruction: "Gondola Transit Center", address: "2291 Mt Werner Cir, Steamboat Springs, CO 80487")
Location.create!(name: "Winter Wonder Grass Tent", instruction: "Gondola Transit Center", address: "2291 Mt Werner Cir, Steamboat Springs, CO 80487")
Location.create!(name: "Lower Knoll Lot", instruction: "Gondola Transit Center", address: "2291 Mt Werner Cir, Steamboat Springs, CO 80487")
Location.create!(name: "Steamboat Grand", instruction: "Front of building", address: "2300 Mt Werner Cir, Steamboat Springs, CO 80487")
Location.create!(name: "Talay Thai", instruction: "Steamboat Grand", address: "2300 Mt Werner Cir, Steamboat Springs, CO 80487")
Location.create!(name: "LaCasa", instruction: "Front entrance  (RLC Shuttle Stop sign)", address: "2315 Ski Trail Ln, Steamboat Springs, CO 80487")
Location.create!(name: "Ptarmigan", instruction: "Front of  building street side  (RLC Shuttle Stop sign)", address: "2322 Apres Ski Way, Steamboat Springs, CO 80487")
Location.create!(name: "Ski Inn", instruction: "Ski Inn 100 parking lot  (RLC Shuttle Stop sign)", address: "2350 Ski Trail Ln, Steamboat Springs, CO 80487")
Location.create!(name: "The Spa Salon", instruction: "Out Front on 5th Street", address: "24 5th St, Steamboat Springs, CO 80487")
Location.create!(name: "Steamboat Tennis Center", instruction: "Front of complex", address: "2500 Pine Grove Rd, Steamboat Springs, CO 80487")
Location.create!(name: "Christy Sports village center", instruction: "front of building", address: "2500 Village Dr, Steamboat Springs, CO 80487")
Location.create!(name: "Iron Waffle", instruction: "front of restaurant", address: "2500 Village Dr, Steamboat Springs, CO 80487")
Location.create!(name: "Steamboat BrauHaus", instruction: "front of building", address: "2500 Village Dr, Steamboat Springs, CO 80487")
Location.create!(name: "Wild Plum", instruction: "front of store", address: "2525 Village Dr, Steamboat Springs, CO 80487")
Location.create!(name: "Dominos", instruction: "Front of restaurant", address: "255 Anglers Dr Ste C, Steamboat Springs, CO 80488")
Location.create!(name: "Waterford", instruction: "Front entrance kiosk (RLC Shuttle Stop sign)", address: "2650 Medicine Springs Rd, Steamboat Springs, CO 80487")
Location.create!(name: "Lodge", instruction: "Front of main office down the stairs  (Shuttle Stop sign)", address: "2700 Village Dr, Steamboat Springs, CO 80487")
Location.create!(name: "Canyon Creek", instruction: "Front of office  (RLC Shuttle Stop sign)", address: "2740 Eagle Ridge Dr, Steamboat Springs, CO 80487")
Location.create!(name: "ButcherKnife", instruction: "front of building", address: "2875 Elk River Road, Steamboat Springs, CO 80487")
Location.create!(name: "Kneading Hands", instruction: "front door", address: "306 Oak St, Steamboat Springs, CO 80487")
Location.create!(name: "Rexs Bar and Grill", instruction: "front of restaurant", address: "3190 S Lincoln Ave, Steamboat Springs, CO 80487")
Location.create!(name: "Wells Fargo", instruction: "rear of building", address: "320 S Lincoln Ave, Steamboat Springs, CO 80487")
Location.create!(name: "Egg & I  ", instruction: "Front of restaurant", address: "325 Anglers Dr, Steamboat Springs, CO 80487")
Location.create!(name: "Natural Grocers", instruction: "front of store", address: "335 Lincoln Ave, Steamboat Springs, CO 80487")
Location.create!(name: "Table 79 Foodbar", instruction: "front of restaurant", address: "345 Lincoln Ave, Steamboat Springs, CO 80487")
Location.create!(name: "Life Essentials Day Spa", instruction: "front of spa", address: "345 Lincoln Ave, Steamboat Springs, CO 80487")
Location.create!(name: "Haymaker", instruction: "front of building", address: "34855 US-40, Steamboat Springs, CO 80487")
Location.create!(name: "One Stop Ski Shop", instruction: "front of store ", address: "35 11th St #130, Steamboat Springs, CO 80487")
Location.create!(name: "Safeway", instruction: "Front of store/Shuttle pick up shelter", address: "37500 E US Hwy 40, Steamboat Springs, CO 80487")
Location.create!(name: "Café Toro", instruction: "front of restaurant", address: "425 Lincoln Ave, Steamboat Springs, CO 80487")
Location.create!(name: "All Season Wellness", instruction: "Out Front on 5th Street", address: "435 5th St, Steamboat Springs, CO 80487")
Location.create!(name: "LOW Country Kitchen", instruction: "Front of Mahogony", address: "435 5th St, Steamboat Springs, CO 80487")
Location.create!(name: "Mahogany Ridge Brewery & Grill", instruction: "Front of Mahogony", address: "435 5th St, Steamboat Springs, CO 80487")
Location.create!(name: "Hair on Earth", instruction: "Front door on Oak Street ", address: "437 Oak St, Steamboat Springs, CO 80487")
Location.create!(name: "Ski & Bike Kare", instruction: "6th street side of store", address: "442 Lincoln Ave, Steamboat Springs, CO 80487")
Location.create!(name: "Fiesta Jalisco", instruction: "Front of restaurant", address: "455 Anglers Dr, Steamboat Springs, CO 80488")
Location.create!(name: "Mambo Italiano", instruction: "backdoor", address: "521 Lincoln Ave, Steamboat Spgs, CO 80487")
Location.create!(name: "Bank of the West", instruction: "Bank of the West 6th st south sign", address: "555 Lincoln Ave, Steamboat Springs, CO 80487")
Location.create!(name: "Ghost Ranch", instruction: "front of restaurant", address: "56 7th St, Steamboat Springs, CO 80487")
Location.create!(name: "Brooklynn's Pizzeria", instruction: "front of restaurant", address: "57 10th St, Steamboat Springs, CO 80477")
Location.create!(name: "Freshies", instruction: "front of restaurant", address: "595 S Lincoln Ave, Steamboat Springs, CO 80487")
Location.create!(name: "Old Town Pub", instruction: "6th street side of restaurant", address: "600 Lincoln Ave, Steamboat Springs, CO 80487")
Location.create!(name: "Steamboat Spa Nail", instruction: "Bank of West Parking lot", address: "601 Lincoln Ave # 104, Steamboat Springs, CO 80487")
Location.create!(name: "Sake2U", instruction: "front of restaurant", address: "609 Yampa St, Steamboat Springs, CO 80487")
Location.create!(name: "Taco Bell or KFC", instruction: "Front of store", address: "625 Snapdragon Way, Steamboat Springs, CO 80477")
Location.create!(name: "Beau Jos Pizza", instruction: "Space Station Gas Station/7th & Lincoln", address: "644 Lincoln Ave, Steamboat Springs, CO 80487")
Location.create!(name: "Winonas Restaurant", instruction: "Space Station Gas Station/7th & Lincoln", address: "644 Lincoln Ave, Steamboat Springs, CO 80487")
Location.create!(name: "Hard Headed", instruction: "Space Station Gas Station/7th & Lincoln", address: "644 Lincoln Ave, Steamboat Springs, CO 80487")
Location.create!(name: "Space Station Gas", instruction: "Space Station Gas Station/7th & Lincoln", address: "644 Lincoln Ave, Steamboat Springs, CO 80487")
Location.create!(name: "Backcountry Deli", instruction: "Space Station Gas Station/7th & Lincoln", address: "644 Lincoln Ave, Steamboat Springs, CO 80487")
Location.create!(name: "Marmot", instruction: "Space Station Gas Station/7th & Lincoln", address: "644 Lincoln Ave, Steamboat Springs, CO 80487")
Location.create!(name: "720 Fusion", instruction: "Space Station Gas Station/7th & Lincoln", address: "644 Lincoln Ave, Steamboat Springs, CO 80487")
Location.create!(name: "Vaqueros Mexican Restuarant & Taqueria", instruction: "Space Station Gas Station/7th & Lincoln", address: "644 Lincoln Ave, Steamboat Springs, CO 80487")
Location.create!(name: "Skull Creek Greek", instruction: "Space Station Gas Station/7th & Lincoln", address: "644 Lincoln Ave, Steamboat Springs, CO 80487")
Location.create!(name: "Salt & Lime", instruction: "Space Station Gas Station/7th & Lincoln", address: "644 Lincoln Ave, Steamboat Springs, CO 80487")
Location.create!(name: "The BARley", instruction: "Space Station Gas Station/7th & Lincoln", address: "644 Lincoln Ave, Steamboat Springs, CO 80487")
Location.create!(name: "Rocky Mountain Pizza", instruction: "Space Station Gas Station/7th & Lincoln", address: "644 Lincoln Ave, Steamboat Springs, CO 80487")
Location.create!(name: "Colorado High 5 Pizza", instruction: "Space Station Gas Station/7th & Lincoln", address: "644 Lincoln Ave, Steamboat Springs, CO 80487")
Location.create!(name: "Noodles & more", instruction: "Space Station Gas Station/7th & Lincoln", address: "644 Lincoln Ave, Steamboat Springs, CO 80487")
Location.create!(name: "Wildhorse Cinema", instruction: "Front of building", address: "655 Marketplace Plaza, Steamboat Springs, CO 80487")
Location.create!(name: "McKnights", instruction: "Front of restaurant", address: "685 Marketplace Plaza, Steamboat Springs, CO 80487")
Location.create!(name: "Blue Sage Pizza", instruction: "Front entrance", address: "685 Marketplace Plaza, Steamboat Springs, CO 80487")
Location.create!(name: "Wildhorse Salon", instruction: "Front Entrance", address: "690 Marketplace Plaza #4, Steamboat Springs, CO 80487")
Location.create!(name: "Rusted Porch", instruction: "Front of restaurant", address: "690 Marketplace Plaza, Steamboat Springs, CO 80487")
Location.create!(name: "Ohanas", instruction: "Out Front", address: "700 Yampa St a105, Steamboat Springs, CO 80487")
Location.create!(name: "Carl's Tavern", instruction: "Out Front", address: "700 Yampa St, Steamboat Springs, CO 80487")
Location.create!(name: "Scratch", instruction: "front of restaurant", address: "700 Yampa St, Steamboat Springs, CO 80487")
Location.create!(name: "Yoga Center of Steamboat", instruction: "front of building", address: "701 Yampa Ave, Steamboat Springs, CO 80487")
Location.create!(name: "E3 Chophouse", instruction: "front of restaurant", address: "701 Yampa St, Steamboat Springs, CO 80487")
Location.create!(name: "Tap House", instruction: "Backdoor", address: "729 Lincoln Ave, Steamboat Springs, CO 80487")
Location.create!(name: "Sweet Pea Restaurant", instruction: "Front of Restaurant", address: "729 Lincoln Ave, Steamboat Springs, CO 80487")
Location.create!(name: "Sunpies Bistro", instruction: "front of restaurant", address: "735 Yampa Ave, Steamboat Springs, CO 80487")
Location.create!(name: "Johnny B Goods", instruction: "Back Door", address: "738 Lincoln Ave, Steamboat Springs, CO 80487")
Location.create!(name: "Aurum Food & Wine", instruction: "front of restaurant", address: "811 Yampa St, Steamboat Springs, CO 80487")
Location.create!(name: "Chief Theatre", instruction: "8th Street South Shuttle Sign", address: "813 Lincoln Ave, Steamboat Springs, CO 80487")
Location.create!(name: "Homesteader", instruction: "8th St South Sign", address: "817 Lincoln Ave, Steamboat Springs, CO 80487")
Location.create!(name: "Cantina", instruction: "backdoor", address: "818 Lincoln Ave, Steamboat Springs, CO 80487")
Location.create!(name: "Schmiggitys", instruction: "8th Street South Shuttle Sign", address: "821 Lincoln Ave, Steamboat Springs, CO 80487")
Location.create!(name: "Roots", instruction: "8th Street South Shuttle Sign", address: "821 Lincoln Ave, Steamboat Springs, CO 80487")
Location.create!(name: "Back Door Grill", instruction: "front of restaurant", address: "825 Oak St, Steamboat Springs, CO 80487")
Location.create!(name: "Celebration of Kids", instruction: "backdoor", address: "831 Lincoln Ave, Steamboat Springs, CO 80487")
Location.create!(name: "Cuginos Pizzeria & Italian Restaurant", instruction: "8th Street South Shuttle Sign", address: "833 Lincoln Ave, Steamboat Springs, CO 80487")
Location.create!(name: "O'Neil's Tavern and Grill", instruction: "8th St South Shuttle Sign", address: "833 Lincoln Ave, Steamboat Springs, CO 80487")
Location.create!(name: "8th St Steakhouse", instruction: "8th St South Shuttle Sign", address: "833 Lincoln Ave, Steamboat Springs, CO 80487")
Location.create!(name: "The Shack", instruction: "8th St South Shuttle Sign", address: "833 Lincoln Ave, Steamboat Springs, CO 80487")
Location.create!(name: "Straightline", instruction: "8th St South Shuttle Sign", address: "833 Lincoln Ave, Steamboat Springs, CO 80487")
Location.create!(name: "Police station ", instruction: "front of building", address: "840 Yampa Ave, Steamboat Springs, CO 80487")
Location.create!(name: "Fuzzywigs", instruction: "9th Street South Shuttle Sign", address: "845 Lincoln Ave, Steamboat Springs, CO 80487")
Location.create!(name: "Lyon Drug", instruction: "9th Street South Shuttle Sign", address: "845 Lincoln Ave, Steamboat Springs, CO 80487")
Location.create!(name: "FM Light & Sons", instruction: "9th Street South Shuttle Sign", address: "845 Lincoln Ave, Steamboat Springs, CO 80487")
Location.create!(name: "Allens", instruction: "9th Street South Shuttle Sign", address: "845 Lincoln Ave, Steamboat Springs, CO 80487")
Location.create!(name: "Steamboat Art Company", instruction: "9th Street South Shuttle Sign", address: "845 Lincoln Ave, Steamboat Springs, CO 80487")
Location.create!(name: "Strings Music Festival", instruction: "front entrance ", address: "900 Strings Rd, Steamboat Springs, CO 80487")
Location.create!(name: "Mountain Tap", instruction: "front of restaurant", address: "910 Yampa St #103, Steamboat Springs, CO 80487")
Location.create!(name: "Yampys Coffees Crepes Cocktails", instruction: "front of restaurant", address: "910 Yampa St #103, Steamboat Springs, CO 80487")
Location.create!(name: "Steamboat Smokehouse", instruction: "backdoor", address: "912 Yampa St #103, Steamboat Springs, CO 80487")
Location.create!(name: "Ciao Gelato", instruction: "backdoor", address: "912 Yampa St #103, Steamboat Springs, CO 80487")
Location.create!(name: "Mazzolas Italian Restaurant", instruction: "backdoor", address: "917 Yampa St #103, Steamboat Springs, CO 80487")
Location.create!(name: "Harwigs", instruction: "Hotel Bristol Parking Lot", address: "917 Yampa St, Steamboat Springs, CO 80487")
Location.create!(name: "Veterans of Foreign Wars (VFW)", instruction: "Back Door", address: "924 Lincoln Ave, Steamboat Springs, CO 80487")
Location.create!(name: "Moose Watch Café", instruction: "front of restaurant", address: "941 Lincoln Ave C, Steamboat Springs, CO 80487")
Location.create!(name: "Sambi Canton Restaurant", instruction: "10th Street South", address: "941 Lincoln Ave, Steamboat Springs, CO 80487")




Shuttle.create(name: "Mike", plate_number: "PBJ-1", current_lat: mk.latitude, current_long: mk.longitude, capacity: 24)
Shuttle.create(name: "Mary", plate_number: "PBJ-2", current_lat: annies.latitude, current_long: annies.longitude, capacity: 24)
Shuttle.create(name: "Max", plate_number: "PBJ-3", current_lat: mk.latitude, current_long: mk.longitude, capacity: 24)
Shuttle.create(name: "John", plate_number: "PBJ-4", current_lat: mk.latitude, current_long: mk.longitude, capacity: 24)
Shuttle.create(name: "Jim", plate_number: "PBJ-5", current_lat: annies.latitude, current_long: annies.longitude, capacity: 24)




#Business.create!(name: "Butcher Knife Brewery", location: bkb, category_id: adult.id, contact_name: "", contact_phone: "", business_type: "Brewery")
#Business.create!(name: "Storm Peak Brewery", location: spb, category_id: adult.id, contact_name: "", contact_phone: "", business_type: "Brewery")
#Business.create!(name: "Smell That Bread", location: smtb, category_id: foodie.id, contact_name: "", contact_phone: "", business_type: "Bakery")
#Business.create!(name: "The Potters Wheel", location: pw, category_id: artistic.id, contact_name: "", contact_phone: "", business_type: "Art Studio")
#Business.create!(name: "Ohanas", location: ohanas, category_id: artistic.id, contact_name: "", contact_phone: "", business_type: "T Shirt Printing")
#Business.create!(name: "Wild West Balloons", location: wwb, category_id: adventure.id, contact_name: "", contact_phone: "", business_type: "Hot Air Baloon Rides")
#Business.create!(name: "Steamboat Gondola", location: gondola, category_id: family.id, contact_name: "", contact_phone: "", business_type: "Gondola Rides")






